name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "*"
      
jobs:
  ci:
    uses: e-scooter-2077/azure-functions-ci/.github/workflows/azure-functions-ci.yml@master
    with:
      release-prefix: Manage Reported Properties
      azure-functionapp-name: 'scooter-monitor-manage-reported-properties'
      project-name: 'EScooter.Monitor.ManageReportedProperties'
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
      
